name: Discord Huh Bot
version: "1.0"
slug: discord_huh_bot
description: "Een simpele Discord bot met /huh command die 'what?' zegt"
arch:
  - amd64
  - armv7
  - aarch64
startup: "application"
boot: "auto"
options:
  discord_token: "VUL_HIER_JE_BOT_TOKEN_IN"
schema:
  discord_token: str
ports: {}
environment:
  - DISCORD_TOKEN=${discord_token}
